// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package database

import (
	"time"
)

type Goal struct {
	ID        int32     `json:"id"`
	Content   string    `json:"content"`
	Name      string    `json:"name"`
	UserID    string    `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	Active    bool      `json:"active"`
}

type RelapsedDay struct {
	Day    time.Time `json:"day"`
	GoalID int32     `json:"goal_id"`
}

type User struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}
